### ISSUE TITLE
LS-PCQA数据使用问题

### ISSUE THREAD

**Issue by orange-416** [lyp22/ResSCNN#10]
您好，我在阅读文章时，对于LS-PCQA数据集的使用有一些疑惑。

  在5.1.1节中，您提到 “To evaluate the performance of the proposed ResSCNN, we conduct evaluation experiments using Part III of the proposed LS-PCQA dataset, where the distorted samples are all labeled by pseudo MOS” ，即仅使用数据集的第三部分进行训练和测试。
![image](https://user-images.githubusercontent.com/58114395/236130423-34a3dec5-d6a2-4ff4-b822-deac57172442.png)

  而在5.1.2节中，您写到 “The training set and testing set from LS-PCQA contain the distorted samples generated from 100 reference point clouds and 4 reference point clouds respectively to avoid overlapping”，这里说的是100个用于训练，4个用于测试，一共使用了104个原始点云的失真版本，即使用整个LS=PCQA数据集来训练和测试。
![image](https://user-images.githubusercontent.com/58114395/236131593-891db814-93ac-4418-9515-a3cdcea47d6f.png)

我想向您确认，您是如何使用LS-PCQA数据集的。是用数据集的part III还是整个数据集？以及4个用于测试的点云具体是哪四个？
期待您的回复！

**Comment by lyp22** [comment]
论文中只使用Part III是因为Part I和II在前面用于主观实验，为了严谨才这样设计实验。

后续经过验证，Part III和整个数据集只差了几百个样本，实验结果差异微小。您可以直接使用整个数据集来训练您的模型。

论文中的用于测试的4个参考点云是按照字母A~Z排序的最后四个点云

**Comment by orange-416** [comment]
谢谢您的说明！
