### ISSUE TITLE
ERROR! Session/line number was not unique in database. History logging moved to new session 881

### ISSUE THREAD

**Issue by samanemami** [lyp22/ResSCNN#2]
I have an issue with `train.py`, when I am running the code it returns the following error, and it crashes;
Do you have any idea how I can solve this issue, please?

Thank you

```log
ERROR! Session/line number was not unique in database. History logging moved to new session 881
```

**Comment by lyp22** [comment]
I have never met such an error. w(°ｏ°)w.
Do you know which line in the code the error happens?

**Comment by samanemami** [comment]
It comes from the Jupyter kernel, I run it with Python and it is working perfectly but the issue is related to `config.py`.
