### ISSUE TITLE
Dataset Issue

### ISSUE THREAD

**Issue by samanemami** [lyp22/ResSCNN#6]
Hi
The following dataset after downloading returns an empty zip;

[Link for whole dataset with generated pseudo MOS](https://sjtueducn-my.sharepoint.com/personal/liuyipeng_sjtu_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fliuyipeng%5Fsjtu%5Fedu%5Fcn%2FDocuments%2Fdistortion&ga=1)

Also, in the following table from the paper, you mentioned these three datasets,
Would you please indicate their related links?

I appreciate it

![image](https://user-images.githubusercontent.com/54855771/205700313-893f6500-a59a-4a7d-8fc6-f231a61240d7.png)

**Comment by lyp22** [comment]
For SJTU-PCQA, you can refer to "https://smt.sjtu.edu.cn/database/point-cloud-subjective-assessment-database/".
For WPC, the paper is "Perceptual Quality Assessment of Colored 3D Point Clouds", and the download link is "https://github.com/qdushl/Waterloo-Point-Cloud-Database".
WPC2.0 is the VPCC part of WPC dataset used in the paper "PQA-Net: Deep No Reference Point Cloud Quality Assessment via Multi-view Projection".

**Comment by lyp22** [comment]
For the link "Link for whole dataset with generated pseudo MOS(https://sjtueducn-my.sharepoint.com/:f:/g/personal/liuyipeng_sjtu_edu_cn/EmZV4in-Nm1Pj2wPOi2DuxQBwBMlamLVLMxRZh8aPonf2Q?e=KQjT1o)", it is OK for me. Maybe you have a network fluctuation, causing damage to the downloaded ZIP. (￣３￣)

**Comment by samanemami** [comment]
Thank you so much fro the references and help

**Comment by samanemami** [comment]
Thank you for your kind reply.

You split the SJTU-PCQA WPC2.0 in a way that training has 0.75, and the test has the rest of the reference samples.
Here, you split only the references, not the distorted images.
Hence, have you only trained the model with the reference?

Thank you
