### ISSUE TITLE
_save_checkpoint

### ISSUE THREAD

**Issue by samanemami** [lyp22/ResSCNN#8]
I am trying the save the trained model with the `_save_checkpoint method`. But it needs the path to dump the model, so I defined the path in `config.resume`, but it tells me that there is no checkpoint found. Meaning that it needs some dumped model already but it does not start to train to dump the model!

**Comment by lyp22** [comment]
emmm, maybe you should read and understand the code completely. `config.resume` is the path to load the checkpoint. If `config.resume` is None, the code will not load the checkpoint. And the function `_save_checkpoint` in the code is used to save the checkpoint and `self._save_checkpoint(epoch)` is just commented out.

**Comment by samanemami** [comment]
Thank you for your reply.
Yes, I found out about the model process.
Last question, if I want to load the saved model, how would it be?
Should I define a subclass from your class?

**Comment by samanemami** [comment]
I found it
Thank you so much for your consideration
